name: Deploy Symfony API with MySQL DB

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install
        working-directory: backend

      - name: Run tests
        run: ./vendor/bin/phpunit tests
        working-directory: backend

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install
        working-directory: backend

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "mkdir -p $DEPLOY_PATH"

          rsync -avz --delete --exclude 'tests' --exclude '.git' backend/ $USERNAME@$HOST:$DEPLOY_PATH

          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "sudo chown -R ubuntu:www-data $DEPLOY_PATH"
          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "sudo chmod -R 775 $DEPLOY_PATH/var $DEPLOY_PATH/vendor $DEPLOY_PATH/public"

          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "echo -e '<IfModule mod_rewrite.c>\nRewriteEngine On\nRewriteCond %{REQUEST_FILENAME} !-f\nRewriteCond %{REQUEST_FILENAME} !-d\nRewriteRule ^ index.php [QSA,L]\n</IfModule>' > $DEPLOY_PATH/public/.htaccess"

          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "sudo a2enmod rewrite"

          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "cd $DEPLOY_PATH && /usr/bin/composer install --no-dev --optimize-autoloader --no-scripts"

          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "cd $DEPLOY_PATH && php bin/console cache:clear --env=prod --no-debug"

          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "sudo systemctl restart apache2"

      - name: Configurar MySQL y ejecutar migraciones
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}

             # Definir los valores directamente (puedes usar secrets si prefieres)
            MYSQL_DATABASE="proyecto"
            MYSQL_USER="templator"
            MYSQL_PASSWORD="templator1234"
            MYSQL_HOST="127.0.0.1"

            # Escapamos la contraseña (si tiene caracteres especiales)
            ENCODED_PASS=$(php -r "echo urlencode('${MYSQL_PASSWORD}');")

            # Construir DATABASE_URL de forma correcta
            echo "DATABASE_URL=mysql://${MYSQL_USER}:${ENCODED_PASS}@${MYSQL_HOST}:3306/${MYSQL_DATABASE}?serverVersion=5.7.40&charset=utf8mb4" > .env.local

            echo "[INFO] .env.local generado:"
            cat .env.local

            # Ejecutar migraciones
            php bin/console doctrine:database:create --if-not-exists --env=prod || true
            php bin/console doctrine:migrations:migrate --no-interaction --env=prod
