name: Deploy Symfony API with MySQL

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install
        working-directory: backend

      - name: Run tests
        run: ./vendor/bin/phpunit tests
        working-directory: backend

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install
        working-directory: backend

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "mkdir -p $DEPLOY_PATH"

          rsync -avz --delete --exclude 'tests' --exclude '.git' backend/ $USERNAME@$HOST:$DEPLOY_PATH

          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "sudo chown -R ubuntu:www-data $DEPLOY_PATH"
          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "sudo chmod -R 775 $DEPLOY_PATH/var $DEPLOY_PATH/vendor $DEPLOY_PATH/public"

          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "echo -e '<IfModule mod_rewrite.c>\nRewriteEngine On\nRewriteCond %{REQUEST_FILENAME} !-f\nRewriteCond %{REQUEST_FILENAME} !-d\nRewriteRule ^ index.php [QSA,L]\n</IfModule>' > $DEPLOY_PATH/public/.htaccess"

          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "sudo a2enmod rewrite"

          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "cd $DEPLOY_PATH && /usr/bin/composer install --no-dev --optimize-autoloader --no-scripts"

          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "cd $DEPLOY_PATH && php bin/console cache:clear --env=prod --no-debug"

          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "sudo systemctl restart apache2"

      - name: Configurar MySQL y ejecutar migraciones
        uses: appleboy/ssh-action@master
        env:
          MYSQL_ROOT_PASSWORD: TemplatorRoot1234
          MYSQL_DATABASE: proyecto
          MYSQL_USER: templator
          MYSQL_PASSWORD: templator1234
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Definir variables para usar dentro del script
            DB_NAME=$MYSQL_DATABASE
            DB_USER=$MYSQL_USER
            DB_PASSWORD=$MYSQL_PASSWORD

            # Instalar MySQL si no está presente
            sudo apt-get update
            sudo apt-get install -y mysql-server

            # Iniciar servicio MySQL
            sudo systemctl start mysql

            # Configurar base de datos y usuario
            sudo mysql -e "CREATE DATABASE IF NOT EXISTS $DB_NAME;"
            sudo mysql -e "CREATE USER IF NOT EXISTS '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASSWORD';"
            sudo mysql -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'localhost';"
            sudo mysql -e "FLUSH PRIVILEGES;"

            # Permitir conexiones remotas (si es necesario)
            sudo sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mysql.conf.d/mysqld.cnf
            sudo systemctl restart mysql

            # Ejecutar migraciones Symfony
            cd ${{ secrets.DEPLOY_PATH }}
            export DATABASE_URL="mysql://$DB_USER:$DB_PASSWORD@127.0.0.1:3306/$DB_NAME?serverVersion=5.7.40"
            php bin/console doctrine:database:create --if-not-exists
            php bin/console doctrine:migrations:migrate --no-interaction
